#Goal - to run end to end devsecops CI pipline
#by prakash
name: DevSecOps CI

on:
    push:
        branches: [advanced]

jobs:
    # ---- ci ---
    #Code stage (with shift left approach )
    code-quality:
         uses: ./.github/workflows/code-quality.yml

    #Secret Scanning stage
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml
    
    #Dependency Scanning stage
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    #Dcoker check
    docker-checks:
        uses: ./.github/workflows/docker-scan.yml 
        secrets: inherit #pass any secrets from the calling workflow to the called wrokflow 

    #SonarQube 
    sonar_qube:
      uses: ./.github/workflows/sonar-scan.yml     
      secrets: inherit

    #code Test
    code-tests:
        uses: ./.github/workflows/code-test.yml

    #push-to-docker-hub:
    docker-push:
        uses: ./.github/workflows/docker-push.yml
        needs: [code-quality,secret-scanning,dependency-scan,docker-checks,code-tests,sonar_qube]
        with:
            IMAGE_TAG: ${{ github.sha }}
        secrets: inherit
    # ------- CD --------
    deploy:
        uses: ./.github/workflows/cd.yml
        needs: [docker-push]
        with:
            IMAGE_TAG: ${{ github.sha }}
        secrets: inherit     
