#Goal - to run end to end devsecops CI pipline

name: DevSecOps CI

on:
    push:
        branches: [advanced]

jobs:
    #Code stage (with shift left approach )
    code-quality:
         uses: ./.github/workflows/code-quality.yml

    #Secret Scanning stage
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml
    
    #Dependency Scanning stage
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    #Dcoker check
    docker-checks:
        uses: ./.github/workflows/docker-scan.yml 
        secrets: inherit #pass any secrets from the calling workflow to the called wrokflow 

    #SonarQube 
    sonar_qube:
      uses: ./.github/workflows/sonar-scan.yml     
      secrets: inherit